name: products
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  gap:
  flutter_svg:
  carousel_slider:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  flutter_gen_runner:
  flutter_native_splash:
  flutter_launcher_icons:
  flutter_bloc:
  bloc:
  freezed:
  collection:
  flutter_animate:
  equatable:
  google_maps_flutter:
  http:
  polyline_codec:  # To decode Google's polyline
  flutter_polyline_points:
  location:
  intl:
  shimmer:
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/banners/
    - assets/category/
    - assets/products/
    - assets/icons/
    - assets/logo/
    - assets/svgs/
    - assets/maps/
    - assets/markers/
    - assets/order_state/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter.ttf


flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true
  colors:
    inputs:
      - assets/colors/colors.xml